language: java
dist: trusty
before_install:
  - chmod +x gradlew
jdk:
  - oraclejdk17
# whitelist
branches:
  only:
    - master
os:
- linux
cache:
directories:
  - $HOME/.gradle
script:
  - ./gradlew check
